Repository equinor/flotilla, pull requests merged in 2022-03, with the labels that each got.

#104 Add logging with api-logger to all endpoints
  backend/src/flotilla/config/log_config.py
  backend/src/flotilla/main.py
Labels: feature

#111 Run as non root for backend and broker
  backend/Dockerfile
  broker/Dockerfile
Labels: improvement

#112 Use numeric user id instead of username
  broker/Dockerfile
Labels: bug

#116 Enable websockets endpoint on port 9001
  broker/mosquitto/config/mosquitto.conf
Labels: feature
