Repository equinor/flotilla, pull requests merged in 2022-08, with the labels that each got.

#309 Add tenant ID to Radix dockerfile
  frontend/Dockerfile.Radix
Labels: bug

#310 Update server certificate to match new key
  broker/mosquitto/config/certs/server-cert.pem
Labels: bug, backend

#323 Rename default in memory robots
  backend/api/Database/Context/InitDb.cs
Labels: improvement

#328 Add dispatch to deployment action
  .github/workflows/repository_dispatch_on_merge.yml
Labels: improvement

#331 Remove openapi dependency from frontend
  frontend/package-lock.json
  frontend/package.json
Labels: improvement, frontend
