Repository equinor/flotilla, pull requests merged in 2022-02, with the labels that each got.

#59 Change default port for frontend to 3001
  docker-compose.yml
  frontend/.gitignore
  frontend/Dockerfile
  frontend/package.json
Labels: improvement

#61 Add mqtt broker
  README.md
  broker/Dockerfile
  broker/README.md
  broker/mosquitto/config/mosquitto.conf
  broker/mosquitto/config/passwd_file
  broker/mosquitto/log/.gitignore
  docker-compose.yml
Labels: feature

#75 Remove sudo from docker-compose commands
  README.md
Labels: documentation

#62 Backend dockerfile
  backend/Dockerfile
  docker-compose.yml
Labels: feature

#92 Add stale tracker for issue and prs
  .github/workflows/stale.yml
Labels: documentation

#97 Update stale.yml
  .github/workflows/stale.yml
Labels: documentation
