Repository equinor/flotilla, pull requests merged in 2022-06, with the labels that each got.

#225 Update Readme
  README.md
  backend/README.md
Labels: documentation

#243 Fix bug where reports were not fetched correctly
  backend/api/Services/ReportService.cs
Labels: bug

#245 Add endpoints to pause and resume a mission
  backend/api/Controllers/RobotController.cs
  backend/api/Database/Models/Report.cs
  backend/api/Services/IsarService.cs
Labels: feature, backend

#261 Update broker readme with TLS instructions
  broker/README.md
Labels: documentation

#262 Update broker readme with cert key format
  broker/README.md
Labels: documentation
