Repository equinor/flotilla, pull requests merged in 2022-10, with the labels that each got.

#365 Update setup script
  setup.sh
Labels: bug

#413 Add custom logging configuration with timestamp
  backend/api/Configurations/ConfigurationBuilderExtensions.cs
  backend/api/Program.cs
Labels: backend, improvement

#416 Display robot as busy if it is in a mission
  frontend/src/components/RobotCards/RobotStatusCard.tsx
  frontend/src/components/RobotCards/RobotStatusChip.tsx
  frontend/src/models/Robot.ts
Labels: bug

#422 Fix wrong name for thermal video string conversion
  backend/api/Database/Models/IsarStep.cs
Labels: bug

#425 Sort robot cards by RobotStatus
  frontend/src/components/RobotCards/RobotStatusView.tsx
Labels: improvement, frontend

#427 Update progress indicator based on task status
  frontend/src/components/MissionOverview/MissionTagDisplay.tsx
  frontend/src/components/MissionOverview/OngoingMissionCard.tsx
  frontend/src/models/IsarTask.ts
Labels: improvement

#432 Remove logging which was dominating the log
  backend/api/Controllers/RobotController.cs
Labels: improvement
