Repository equinor/flotilla, pull requests merged in 2022-05, with the labels that each got.

#148 Add user sign in to frontend
  backend/src/flotilla/api/authentication.py
  backend/src/flotilla/settings/settings.env
  backend/src/flotilla/settings/settings.py
  broker/README.md
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/authConfig.tsx
  frontend/src/components/SignInPage/ApiCaller.tsx
  frontend/src/components/SignInPage/ProfileContent.tsx
  frontend/src/components/SignInPage/SignInButton.tsx
  frontend/src/components/SignInPage/SignInPage.tsx
  frontend/src/index.tsx
  frontend/src/models/schema.ts
  frontend/tsconfig.json
Labels: feature

#188 Update readme for dotnet
  backend/README.md
Labels: documentation

#183 Add start and stop endpoints
  backend/api.test/TestEventController.cs
  backend/api.test/TestRobotController.cs
  backend/api.test/api.test.csproj
  backend/api/Context/FlotillaDbContext.cs
  backend/api/Context/InitDb.cs
  backend/api/Controllers/EventController.cs
  backend/api/Controllers/ReportController.cs
  backend/api/Controllers/RobotController.cs
  backend/api/Database/Models/Event.cs
  backend/api/Database/Models/Report.cs
  backend/api/Database/Models/ReportEntry.cs
  backend/api/Database/Models/Robot.cs
  backend/api/Program.cs
  backend/api/Services/IsarService.cs
  backend/api/Services/ReportService.cs
  backend/api/Services/RobotService.cs
  backend/api/Utilities/Exceptions.cs
  backend/api/appsettings.json
Labels: dotnet

#203 Run csharpier to format all files
  .github/workflows/backend_lint_and_test.yml
  backend/.config/dotnet-tools.json
  backend/README.md
  backend/api.test/TestEventController.cs
  backend/api/Configurations/ConfigureSwagger.cs
  backend/api/Controllers/EventController.cs
  backend/api/Controllers/ReportController.cs
  backend/api/Controllers/RobotController.cs
  backend/api/Database/Models/Event.cs
  backend/api/Database/Models/Report.cs
  backend/api/Database/Models/ReportEntry.cs
  backend/api/Database/Models/Robot.cs
  backend/api/Program.cs
  backend/api/Services/EchoService.cs
  backend/api/Services/EventService.cs
  backend/api/Services/IsarService.cs
  backend/api/Services/KeyVaultService.cs
  backend/api/Services/ReportService.cs
  backend/api/Services/RobotService.cs
Labels: backend, improvement
