Repository equinor/flotilla, pull requests merged in 2023-04, with the labels that each got.

#729 Convert angle in degrees from echo to radians
  backend/api/Services/EchoService.cs
Labels: bug

#725 Filter missions by currently selected asset
  frontend/src/api/ApiCaller.tsx
  frontend/src/models/MissionQueryParameters.ts
Labels: improvement, frontend

#734 Add DB changes to release notes
  .github/release.yml
Labels: documentation

#740 Fix workflow syntaxt
  .github/workflows/deploy_to_development.yml
  .github/workflows/deploy_to_staging.yml
  .github/workflows/promoteToProduction.yml
  .github/workflows/publish_component.yml
Labels: bug

#741 Fix env variables in workflows
  .github/workflows/deploy_to_development.yml
  .github/workflows/deploy_to_staging.yml
  .github/workflows/promoteToProduction.yml
Labels: bug

#745 Parameterize username and password to container registry
  .github/workflows/deploy_to_development.yml
  .github/workflows/deploy_to_staging.yml
  .github/workflows/publish_component.yml
Labels: bug

#746 Change container registry username to secret
  .github/workflows/deploy_to_development.yml
  .github/workflows/deploy_to_staging.yml
  .github/workflows/publish_component.yml
Labels: bug

#749 Fix username in deployment pipelines
  .github/workflows/deploy_to_staging.yml
  .github/workflows/promote_to_production.yml
  .github/workflows/update_aurora_deployment.yml
Labels: bug

#752 Update README with deployments in Aurora
  README.md
Labels: documentation

#753 Add deployment triggers to deployment workflows
  .github/workflows/deploy_to_development.yml
  .github/workflows/deploy_to_staging.yml
  .github/workflows/promote_to_production.yml
Labels: improvement

#763 Add support for scheduling custom json missions
  backend/api/Controllers/MissionController.cs
  backend/api/Controllers/Models/CustomMissionQuery.cs
  backend/api/Database/Models/Inspection.cs
  backend/api/Database/Models/MissionTask.cs
Labels: feature, backend

#771 Set tag to optional in IsarMission
  backend/api/Services/Models/IsarMissionDefinition.cs
Labels: bug, backend

#774 Add optional tag to custom mission
  backend/api/Controllers/Models/CustomMissionQuery.cs
  backend/api/Database/Models/MissionTask.cs
Labels: feature, backend
