Repository equinor/flotilla, pull requests merged in 2023-01, with the labels that each got.

#481 Add predefined poses for SST area
  backend/api/Utilities/PredefinedPoses.json
Labels: improvement

#478 Add error handling callback for login
  frontend/src/index.tsx
Labels: improvement, frontend

#514 Fix homepage bug in package.json
  frontend/package.json
Labels: bug

#526 Add predefined poses for narrow pathway
  backend/api/Utilities/PredefinedPoses.json
Labels: documentation

#537 Fix mission not including map properties
  backend/api/Database/Models/MissionMap.cs
  backend/api/Services/Models/TransformationMatrices.cs
Labels: bug, backend
