Repository equinor/flotilla, pull requests merged in 2024-10, with the labels that each got.

#1756 Fix error message
  backend/api/Services/MissionSchedulingService.cs
Labels: bug

#1764 Update versions in github actions
  .github/workflows/backend_lint_and_test.yml
  .github/workflows/frontend_lint_and_test.yml
  .github/workflows/notifyMigrationChanges.yml
  .github/workflows/notifyPossibleMigrationUpdate.yml
  .github/workflows/promote_to_production.yml
  .github/workflows/publish_component.yml
  .github/workflows/scan_with_trufflehog.yml
  .github/workflows/updateDatabase.yml
  .github/workflows/update_aurora_deployment.yml
  .github/workflows/verifyMigrations.yml
Labels: improvement

#1766 Improve consistency of tests by removing InitDb in tests
  backend/README.md
  backend/api.test/Client/AreaTests.cs
  backend/api.test/Client/MissionTests.cs
  backend/api.test/Client/RobotTests.cs
  backend/api.test/Client/RoleAccessTests.cs
  backend/api.test/Database/DatabaseUtilities.cs
  backend/api.test/DbContextTestSetup.cs
  backend/api.test/EventHandlers/TestMissionEventHandler.cs
  backend/api.test/Mocks/BlobServiceMock.cs
  backend/api.test/Mocks/IsarServiceMock.cs
  backend/api.test/Mocks/StidServiceMock.cs
  backend/api.test/Services/MissionService.cs
  backend/api.test/Services/RobotService.cs
  backend/api.test/api.test.csproj
  backend/api/Configurations/CustomServiceConfigurations.cs
  backend/api/Controllers/AccessRoleController.cs
  backend/api/Controllers/DeckController.cs
  backend/api/Controllers/InstallationController.cs
  backend/api/Controllers/MissionSchedulingController.cs
  backend/api/Controllers/PlantController.cs
  backend/api/Database/Context/InitDb.cs
  backend/api/Database/Models/Robot.cs
  backend/api/EventHandlers/MqttEventHandler.cs
  backend/api/Services/AreaService.cs
  backend/api/Services/DeckService.cs
  backend/api/Services/InstallationService.cs
  backend/api/Services/LocalizationService.cs
  backend/api/Services/MissionSchedulingService.cs
  backend/api/Services/PlantService.cs
  backend/api/Services/ReturnToHomeService.cs
  backend/api/Services/RobotModelService.cs
  backend/api/Services/RobotService.cs
  backend/api/appsettings.Local.json
  backend/api/appsettings.json
Labels: improvement

#1780 Show robot as busy when driving home
  backend/api/Database/Context/InitDb.cs
  frontend/src/components/Displays/RobotDisplays/RobotStatusIcon.tsx
Labels: improvement, frontend

#1781 Fix flotilla not reporting connection issues after broker goes down
  backend/api/Services/RobotService.cs
Labels: bug, backend
