Repository equinor/flotilla, pull requests merged in 2025-08, with the labels that each got.

#2331 Remove api calls for tab-components that are not viewed
  frontend/src/components/Pages/FrontPage/FrontPage.tsx
Labels: bug

#2277 Assume isarMissionId is identical to mission.Id
  backend/api.test/Database/DatabaseUtilities.cs
  backend/api.test/EventHandlers/TestMissionEventHandler.cs
  backend/api.test/Utilities/TestObjectGenerator.cs
  backend/api/Controllers/Models/MissionRunResponse.cs
  backend/api/Database/Models/MissionRun.cs
  backend/api/EventHandlers/MqttEventHandler.cs
  backend/api/Services/MissionRunService.cs
  backend/api/Services/MissionSchedulingService.cs
  backend/api/Services/Models/IsarMissionDefinition.cs
  frontend/src/models/Mission.ts
Labels: breaking-change

#2364 Allow server sent events in signalr
  backend/api/Program.cs
  frontend/src/components/Contexts/SignalRContext.tsx
Labels: frontend
